### PR TITLE
unzip

### PR DESCRIPTION
**Pull request by guitcastro**
#3

### CODE REVIEW

**Comment by viktorbenei** [comment]
So, the question is, which would be the better solution: including zip / unzip in the image by default, or to use the `deps` dependency declaration in the steps (ex: https://github.com/bitrise-io/steps-activate-ssh-key/blob/master/step.yml#L25).

The general guideline is to only pre-install the tools which are absolutely required or take a long time to install, and let everything else to be handled by step `deps`.

The reason is: if you want to run the `bitrise` CLI on your own Mac/PC the `deps` will be handled automatically, but the things defined / pre-installed in base images have to be installed manually.

So, the general guideline is to handle dependencies with step `deps` always, and pre-install things in the environment to speed up the process - but this doesn't eliminate the need to declare these as `deps`!

I'll leave this PR open, as it might be useful in the future, but first `unzip` should be added as `deps` to the related Steps.

**Comment by guitcastro** [comment]
If I specify zip in `deps` it will be installed before the step execution ?

**Comment by viktorbenei** [comment]
Sure, that's the point of `deps` ;)

**Comment by viktorbenei** [comment]
To be precise: `bitrise` will check whether the dependency is available, and install it only if not found.

**Comment by viktorbenei** [comment]
we decided that `unzip` is a nice-to-have tool, will be available in the next Docker image on bitrise.io, later today

**Pull request merged**
